name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: PNPM cache setup
        uses: GustavEikaas/pnpm-setup@v0.0.2

      - name: Pnpm install
        run: "pnpm i"

      - name: Build
        shell: bash
        run: pnpm build
