name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: PNPM setup
        uses: GustavEikaas/pnpm-setup/.github/actions/pnpm-setup@main

      - name: Build
        shell: bash
        run: pnpm build
