name: workflow, no args
run-name: ${{github.event.actor}} is running
on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: sleep
        shell: bash
        run: sleep 60

      - name: echo
        shell: bash
        run: echo finished

