name: nvim debug
on:
  workflow_dispatch:
    inputs:
      name:
        type: choice
        description: Who to greet
        options:
          - monalisa
          - cschleiden
      message:
        required: true
        description: message
      use-emoji:
        type: boolean
        description: Include 🎉🤣 emojis
      environment:
        type: environment
        description: message

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: sleep
        shell: bash
        run: usleep 60

      - name: echo
        shell: bash
        run: |
          echo ${{ github.event.inputs.message}}
          echo ${{ github.event.inputs.name }}
          echo ${{ github.event.inputs.use-emoji}}
          echo ${{ github.event.inputs.environment}}
