name: File creator test
on:
  workflow_dispatch:
    inputs:
      name:
        type: choice
        description: Who to greet
        options:
          - monalisa
          - cschleiden
      message:
        required: true
        description: message
      use-emoji:
        type: boolean
        description: Include 🎉🤣 emojis
      environment:
        type: environment
        description: message

jobs:
  test:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Build
        shell: bash
        run: echo ${{inputs.name}}
