name: Publish changed
on:
  push:
    branches:
      - main
jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: PNPM setup
        uses: ./.github/actions/pnpm-setup

      - name: Build
        shell: bash
        run: pnpm build

      # Set token
      - run: pnpm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"

      # Publish all packages in the workspace which version still does not exist
      - run: pnpm publish --no-git-checks
