name: Publish changed
on:
  push:
    branches:
      - main
jobs:
  publish:
    environment: npm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: PNPM setup
        uses: ./.github/actions/pnpm-setup

      - name: Build
        shell: bash
        run: pnpm build

      # Set token
      - run: pnpm config set '//registry.npmjs.org/:_authToken' "${{secrets.NPM_AUTH_TOKEN}}"

      # -r makes pnpm to only run this workflow on packages where version has changed
      - run: pnpm -r publish
