name: Publish changed
on:
  push:
    branches:
      - main
jobs:
  publish:
    environment: npm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: PNPM setup
        uses: ./.github/actions/pnpm-setup

      - name: Build
        shell: bash
        run: pnpm build

      # Set token
      - run: pnpm config set '//registry.npmjs.org/:_authToken' "${{secrets.NPM_AUTH_TOKEN}}"

      # Publish all packages in the workspace which version still does not exist
      - run: pnpm publish
