name: File creator

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies & build
        run: npm run first-time-setup

      - name: "Test file creator"
        run: npx ts-node --esm ./src/file-creator/index.ts

      - name: Validate
        run: cat ./out/main.tsx.template
