name: File creator test

on:
  push:

jobs:
  test:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies & build
        run: npm run first-time-setup

      - name: "Test file creator"
        run: npx ts-node --esm ./.github/workflows/file-creator.ts

      - name: Validate
        run: cat ./out/main.tsx
